

spring:
  datasource:
    username: root
    password: zcx1206
    url: jdbc:mysql://localhost:3306/channelt?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: zcx5672
    virtual-host: /vir